// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyOrganizator.Modelo.Tables;

namespace MyOrganizator.Modelo.Migrations
{
    [DbContext(typeof(TimeOrganizatorContext))]
    [Migration("20220920144158_addTableSemana")]
    partial class addTableSemana
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionProyectoPorDia", b =>
                {
                    b.Property<int>("AsignacionProyectoPorDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AsignacionTipoProyectoPorDiaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.HasKey("AsignacionProyectoPorDiaId");

                    b.HasIndex("AsignacionTipoProyectoPorDiaId");

                    b.ToTable("AsignacionesProyectoPorDia");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionTipoProyectoPorDia", b =>
                {
                    b.Property<int>("AsignacionTipoProyectoPorDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.Property<int>("TipoProyectoId")
                        .HasColumnType("int");

                    b.HasKey("AsignacionTipoProyectoPorDiaId");

                    b.HasIndex("TipoProyectoId");

                    b.ToTable("AsignacionesTipoProyectoPorDia");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.DiaSemana", b =>
                {
                    b.Property<int>("DiaSemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalHoras")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaSemanaId");

                    b.ToTable("DiaSemana");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Parametros", b =>
                {
                    b.Property<int>("ParametrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParametrosId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.PlanActividad", b =>
                {
                    b.Property<int>("PlanActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenEjecucion")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoActividadId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTiempoId")
                        .HasColumnType("int");

                    b.HasKey("PlanActividadId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("TipoTiempoId");

                    b.ToTable("PlanActividads");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AsignacionProyectoId")
                        .HasColumnType("int");

                    b.Property<int?>("AsignacionProyectoPorDiaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoId");

                    b.HasIndex("AsignacionProyectoPorDiaId");

                    b.HasIndex("TipoProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TiempoReal", b =>
                {
                    b.Property<int>("TiempoRealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanActividadId")
                        .HasColumnType("int");

                    b.HasKey("TiempoRealId");

                    b.HasIndex("PlanActividadId");

                    b.ToTable("TiempoReals");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoActividad", b =>
                {
                    b.Property<int>("TipoActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoProyectoId")
                        .HasColumnType("int");

                    b.HasKey("TipoActividadId");

                    b.HasIndex("TipoProyectoId");

                    b.ToTable("TipoActividads");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoProyecto", b =>
                {
                    b.Property<int>("TipoProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TipoProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TipoProyectos");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoTiempo", b =>
                {
                    b.Property<int>("TipoTiempoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTiempoId");

                    b.ToTable("TipoTiempos");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionProyectoPorDia", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.AsignacionTipoProyectoPorDia", "AsignacionTipoProyectoPorDia")
                        .WithMany("AsignacionesProyectoPorDia")
                        .HasForeignKey("AsignacionTipoProyectoPorDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionTipoProyectoPorDia");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionTipoProyectoPorDia", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.TipoProyecto", "TipoProyecto")
                        .WithMany("AsignacionesTipoProyectoPorDia")
                        .HasForeignKey("TipoProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProyecto");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.PlanActividad", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.Proyecto", "Proyecto")
                        .WithMany("PlanesActividad")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyOrganizator.Modelo.Tables.TipoActividad", "TipoActividad")
                        .WithMany("PlanesActividad")
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyOrganizator.Modelo.Tables.TipoTiempo", "TipoTiempo")
                        .WithMany("PlanesActividad")
                        .HasForeignKey("TipoTiempoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("TipoActividad");

                    b.Navigation("TipoTiempo");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Proyecto", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.AsignacionProyectoPorDia", "AsignacionProyectoPorDia")
                        .WithMany("Proyectos")
                        .HasForeignKey("AsignacionProyectoPorDiaId");

                    b.HasOne("MyOrganizator.Modelo.Tables.TipoProyecto", "TipoProyecto")
                        .WithMany("Proyectos")
                        .HasForeignKey("TipoProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyOrganizator.Modelo.Tables.Usuario", "Usuario")
                        .WithMany("Proyectos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionProyectoPorDia");

                    b.Navigation("TipoProyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TiempoReal", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.PlanActividad", "PlanActividad")
                        .WithMany("TiemposReales")
                        .HasForeignKey("PlanActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanActividad");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoActividad", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.TipoProyecto", "TipoProyecto")
                        .WithMany("TiposActividad")
                        .HasForeignKey("TipoProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProyecto");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoProyecto", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.Usuario", "Usuario")
                        .WithMany("TiposProyecto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Usuario", b =>
                {
                    b.HasOne("MyOrganizator.Modelo.Tables.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionProyectoPorDia", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.AsignacionTipoProyectoPorDia", b =>
                {
                    b.Navigation("AsignacionesProyectoPorDia");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.PlanActividad", b =>
                {
                    b.Navigation("TiemposReales");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Proyecto", b =>
                {
                    b.Navigation("PlanesActividad");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoActividad", b =>
                {
                    b.Navigation("PlanesActividad");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoProyecto", b =>
                {
                    b.Navigation("AsignacionesTipoProyectoPorDia");

                    b.Navigation("Proyectos");

                    b.Navigation("TiposActividad");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.TipoTiempo", b =>
                {
                    b.Navigation("PlanesActividad");
                });

            modelBuilder.Entity("MyOrganizator.Modelo.Tables.Usuario", b =>
                {
                    b.Navigation("Proyectos");

                    b.Navigation("TiposProyecto");
                });
#pragma warning restore 612, 618
        }
    }
}
